language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml
      - postgis postgresql-9.6-postgis-2.3
      - postgresql-9.6-postgis-2.3-scripts

env:
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

before_script:
  - if [ "$TESTS" -e "1" ] ; then psql -U postgres -d postgres -c "create extension postgis"; fi
  - if [ "$TESTS" -e "1" ] ; then psql -U postgres -d postgres -c "create extension postgis_topology"; fi

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
